/*
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfCert.
 *
 * wolfCert is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfCert is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with wolfCert.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef WOLFCERT_TYPES_H
#define WOLFCERT_TYPES_H

/* Compile-time feature configuration. Pulled in here so every wolfCert
 * header/source sees a consistent WOLFCERT_HAVE_* view without relying on -D
 * flags.
 *
 * Two ways to supply it, mirroring wolfSSL's options.h vs user_settings.h:
 *   - default: <wolfcert/options.h>, GENERATED by the build (CMake's
 *     configure_file or autoconf's config.status, from wolfcert/options.h.in).
 *     If it is missing, (re-)run cmake/configure rather than looking for a
 *     checked-in copy.
 *   - WOLFCERT_USER_SETTINGS defined: the integrator supplies user_settings.h
 *     on the include path and runs no wolfCert configure step (header-only
 *     builds driven by an external build system, e.g. an MCU toolchain).
 *
 * Either way, wolfcert/check_config.h then validates the resulting
 * WOLFCERT_HAVE_* set (and the underlying wolfSSL feature set) at compile
 * time, so a bad config fails loudly with a clear #error. */
#ifdef WOLFCERT_USER_SETTINGS
    #include "user_settings.h"
#else
    #include <wolfcert/options.h>
#endif
#include <wolfcert/check_config.h>

#include <stddef.h>
#include <stdint.h>

#include <wolfcert/api.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    WOLFCERT_PROTO_EST  = 1,
    WOLFCERT_PROTO_SCEP = 2
} WolfCertProtocol;

/* Serialization format for certificate/key buffers. */
typedef enum {
    WOLFCERT_ENCODING_PEM = 0,
    WOLFCERT_ENCODING_DER = 1
} WolfCertEncoding;

/* Deprecated: use WolfCertTransport, never both on one config (BAD_ARG). An
 * fd cannot carry a non-socket handle, which is why this is going away.
 * Return it blocking; its own SO_RCVTIMEO / SO_SNDTIMEO then bound the I/O. */
typedef int (*WolfCertConnectFn)(const char* host, int port,
                                 int timeout_ms, void* ctx);

/* Pluggable transport, carrying TLS records and plain HTTP alike. NULL in a
 * config selects the built-in POSIX one; it must outlive its connections.
 * Contract: docs/ARCHITECTURE.md section 4.6. */
typedef struct WolfCertTransport {
    /* *conn is opaque and never NULL-tested, so 0 is a valid handle. */
    int  (*connect)(void* ctx, const char* host, int port,
                    int timeout_ms, void** conn);
    /* Bytes moved, or a negative WOLFCERT_ERR_*; never 0 (orderly close is
     * CONN_CLOSED). timeout_ms: 0 never blocks, > 0 caps it, < 0 waits. */
    int  (*read)(void* ctx, void* conn, uint8_t* buf, size_t len,
                 int timeout_ms);
    int  (*write)(void* ctx, void* conn, const uint8_t* buf, size_t len,
                  int timeout_ms);
    /* Runs exactly once per successful connect, error paths included. */
    int  (*disconnect)(void* ctx, void* conn);
    void* ctx;   /* transport-wide, e.g. the stack instance */
} WolfCertTransport;

typedef enum {
    WOLFCERT_KEY_RSA     = 1,
    WOLFCERT_KEY_ECC     = 2,
    WOLFCERT_KEY_ED25519 = 3,
    WOLFCERT_KEY_ED448   = 4,
    WOLFCERT_KEY_MLDSA44 = 5,
    WOLFCERT_KEY_MLDSA65 = 6,
    WOLFCERT_KEY_MLDSA87 = 7
} WolfCertKeyType;

/* Offloading is expressed generically through wolfSSL's CryptoCb devId.
 * The application registers its own CryptoCb (PKCS#11, TPM, HSM, custom),
 * then passes the returned devId here. WOLFCERT_DEVID_SOFTWARE selects
 * pure software operations. The library never registers a CryptoCb itself. */
#define WOLFCERT_DEVID_SOFTWARE (-1)

typedef struct {
    WolfCertKeyType type;
    int             param;       /* RSA bits (2048/3072/4096) or ECC curve id */
    int             dev_id;      /* wolfSSL CryptoCb devId; -1 for software */
    const char*     key_label;   /* optional backend identifier for persistent keys */
    void*           heap;        /* optional heap hint; NULL = default */
} WolfCertKeyCfg;

/* Callback invoked by wolfcert_csr_build() after the standard fields are
 * populated. `cert` is a wolfSSL `Cert*` cast to `void*` so that the
 * caller can reach into fields like custom extension OIDs or SAN types
 * that wolfCert doesn't expose directly. Returns WOLFCERT_OK on success
 * (build continues), any error (build aborts). */
typedef int (*WolfCertCsrCustomizeCb)(void* wolfssl_cert, void* ctx);

typedef struct {
    /* All pointers are caller-owned. NULL lists => none. */
    const char*        subject_dn;         /* e.g. "CN=device-123,O=Acme".
                                            * Literal ',' and '=' in values
                                            * are NOT supported - use the
                                            * customize callback for those. */
    const char* const* san_dns;            /* array of length san_dns_len */
    size_t             san_dns_len;
    const char* const* san_ip;             /* textual IPv4/IPv6 */
    size_t             san_ip_len;
    const char* const* san_uri;
    size_t             san_uri_len;
    const char* const* san_email;          /* rfc822Name (e.g. "dev@example.com") */
    size_t             san_email_len;
    const char*        key_usage;          /* comma-separated */
    const char*        extended_key_usage; /* comma-separated EKU names or OIDs */

    /* Optional: raw CSR attribute DER (one or more Attributes). Kept as
     * an interop hook, but NOT currently injected into the signed CSR
     * by `wolfcert_csr_build` - wolfSSL's public Cert struct has no
     * stable setter for arbitrary-OID CSR attributes. Callers that
     * need a non-standard attribute reach into the wolfSSL Cert* via
     * the `customize` callback below. The typed hints that a
     * `/csrattrs` response carries (key algorithm, hash, challenge
     * password, extension request) are instead applied via
     * `wolfcert_csr_attrs_apply` onto the structured fields of this
     * struct and onto WolfCertKeyCfg, and those are honoured normally
     * by `wolfcert_csr_build`. */
    const uint8_t*     csr_attributes_der;
    size_t             csr_attributes_der_len;

    /* Optional: PKCS#9 challengePassword (OID 1.2.840.113549.1.9.7) to
     * embed as a CSR attribute. Used by SCEP (RFC 8894 section 2.9) to
     * authenticate the enrollment request. NULL means no challengePassword
     * attribute is emitted. Max length CTC_NAME_SIZE - 1 (wolfSSL limit). */
    const char*        challenge_password;

    /* Optional: pinned signature hash size in bits (256 / 384 / 512).
     * Overrides the per-key-type default when non-zero. 0 = "use the
     * algorithm's default" (RSA -> SHA-256, ECC curve-matched,
     * Ed25519/Ed448/ML-DSA ignore this field). Populated automatically
     * by `wolfcert_csr_attrs_apply` when the server pinned a signature
     * algorithm via /csrattrs. */
    int                preferred_hash;

    /* Optional: invoked after standard fields are set, before signing. */
    WolfCertCsrCustomizeCb customize;
    void*                  customize_ctx;
} WolfCertCertMeta;

/* SCEP transactionID derivation (WolfCertScepServerOpts.txid_mode). */
typedef enum {
    WOLFCERT_SCEP_TXID_RANDOM      = 0, /* random 16-byte value, hex-encoded (default) */
    WOLFCERT_SCEP_TXID_PUBKEY_HASH = 1  /* SHA-256 of the signer public key */
} WolfCertScepTxidMode;

/* SCEP request content-encryption cipher (WolfCertScepServerOpts.content_cipher).
 * AUTO keeps the RFC 8894 caps-driven default; the explicit values force a
 * cipher for a known peer (e.g. a wolfSCEP deployment that requires AES-256). */
typedef enum {
    WOLFCERT_SCEP_CIPHER_AUTO   = 0, /* AES-128-CBC when the CA advertises AES, else 3DES */
    WOLFCERT_SCEP_CIPHER_AES128 = 1,
    WOLFCERT_SCEP_CIPHER_AES256 = 2,
    WOLFCERT_SCEP_CIPHER_DES3   = 3
} WolfCertScepContentCipher;

/* Which messageType a SCEP renewal carries (WolfCertScepServerOpts.renewal_msg_type).
 * Either way the pkiMessage is signed by the certificate being replaced; only the
 * messageType attribute changes. RENEWAL_REQ is RFC 8894 section 3.3.1's
 * messageType 17. PKCS_REQ sends 19 instead, which is what CAs that predate
 * RenewalReq expect for a renewal. */
typedef enum {
    WOLFCERT_SCEP_RENEWAL_MSG_RENEWAL_REQ = 0, /* messageType 17 (default) */
    WOLFCERT_SCEP_RENEWAL_MSG_PKCS_REQ    = 1  /* messageType 19 */
} WolfCertScepRenewalMsgType;

/* EST-only knobs, reached through WolfCertServerCfg.proto_opts.est. */
typedef struct {
    /* HTTP Basic credentials (RFC 7030 section 3.2.3), optional. Sent on
     * every one-shot request and on every request a keep-alive session
     * issues. */
    const char* username;
    const char* password;

    /* TLS 1.3 post-handshake authentication opt-in (RFC 8446 section 4.6.2).
     * Read only by the keep-alive EST session API; the one-shot
     * per-request transports don't keep a session to re-auth on. When
     * set, client_cert / client_key are loaded on the SSL even
     * when the initial handshake is anonymous so that wolfSSL can
     * answer a later CertificateRequest from the server transparently. */
    int allow_post_handshake_auth;

    /* Auto-discovery of /csrattrs hints before enrolment. When
     * non-zero, `wolfcert_client_enroll` fetches the server's
     * /.well-known/est/csrattrs response, parses it, and applies the
     * typed hints (preferred key type + curve / RSA bits,
     * preferred signature hash) to a writable copy of the caller's
     * `key_cfg` and `meta` before generating the key and building the
     * CSR. Caller-supplied explicit values always win - this only
     * fills fields the caller left at their zero defaults.
     *
     * Silently a no-op when the server responds with 204 No Content
     * (no policy advertised). */
    int auto_csrattrs;
} WolfCertEstServerOpts;

/* SCEP-only knobs, reached through WolfCertServerCfg.proto_opts.scep.
 * Every field is zero-init-safe: the all-zero value of each preserves
 * wolfCert's pre-existing behavior, so a caller only sets what it needs. */
typedef struct {
    /* CA identifier sent as the `message` query parameter on GetCACaps and
     * GetCACert (RFC 8894 section 3.5.2 / 4.2), used to select a specific CA on
     * a multi-CA responder. NULL (the default) omits the parameter. */
    const char*               ca_id;

    /* How the enrollment pkiMessage transactionID is derived. RANDOM (default)
     * uses fresh RNG bytes; PUBKEY_HASH derives it from the signer public key
     * (RFC 8894 section 3.2.1) so retries of the same key reuse one ID. */
    WolfCertScepTxidMode      txid_mode;

    /* Content-encryption cipher for the request EnvelopedData. AUTO (default)
     * keeps the RFC 8894 caps-driven choice (AES-128-CBC, else 3DES); an
     * explicit value forces that cipher for a peer that requires it. */
    WolfCertScepContentCipher content_cipher;

    /* messageType a renewal carries. The default is RFC 8894's RenewalReq;
     * PKCS_REQ sends messageType 19 with the same existing-certificate signer,
     * for a CA that predates RenewalReq. Read only by the renewal entry
     * points. Check WolfCertScepCaps.renewal to see whether the CA advertises
     * the RFC form before choosing. */
    WolfCertScepRenewalMsgType renewal_msg_type;
} WolfCertScepServerOpts;

typedef struct {
    WolfCertProtocol protocol;
    const char*      server_url;     /* e.g. https://ca.example/.well-known/est */
    const uint8_t*   trust_anchors; /* bootstrap trust for TLS; PEM or DER; optional */
    size_t           trust_anchors_len;
    int              verify_server;  /* 0 = explicit-TA bootstrap, 1 = full verify */
    int              timeout_ms;     /* per-request timeout; 0 = default */

    /* Optional client identity for mutual TLS. Set both `client_cert`
     * and `client_key` to present a client certificate during the TLS
     * handshake. Used for bootstrap-with-factory-identity enrollment and
     * for any other EST/SCEP deployment that requires mTLS to the RA/CA.
     * Each buffer may be PEM or DER; the format is auto-detected.
     *
     * EST `/simplereenroll` always uses the cert-being-renewed as its
     * implicit mTLS identity; these fields let callers supply a different
     * (typically more privileged) identity for `/simpleenroll` or for
     * anonymous operations like `/cacerts` when the server mandates
     * mutual auth. */
    const uint8_t*   client_cert;
    size_t           client_cert_len;
    const uint8_t*   client_key;
    size_t           client_key_len;

    /* Hard cap on the size of a single HTTP response body. 0 means use
     * the library default (64 KiB). Bounds heap pressure; an MCU build
     * typically sets this explicitly. */
    size_t           max_response_bytes;

    WolfCertConnectFn connect_cb;
    void*             connect_ctx;

    /* Protocol-specific options, selected by `protocol`: one connection is
     * either EST or SCEP, never both, so the two option sets share storage.
     * Every member is zero-init-safe - leaving the union untouched keeps the
     * default behavior of both protocols. The arm that does not match
     * `protocol` is never read.
     *
     * Because `protocol` is the discriminator, it must be set on every config
     * handed to a protocol-specific entry point, not just to the generic
     * wolfcert_client_* calls. A wolfcert_est_* call rejects a config whose
     * protocol is not WOLFCERT_PROTO_EST with WOLFCERT_ERR_BAD_ARG, and the
     * wolfcert_scep_* calls do the same for WOLFCERT_PROTO_SCEP, rather than
     * reinterpret the other arm's storage. */
    union {
        WolfCertEstServerOpts  est;
        WolfCertScepServerOpts scep;
    } proto_opts;

    /* Heap hint for any library-internal allocations made while servicing
     * this request. NULL = library default. */
    void*            heap;

    const WolfCertTransport* transport;
} WolfCertServerCfg;

/* A caller-owned byte buffer produced by the library. Free with
 * wolfcert_buffer_free(). The buffer struct itself may have been allocated
 * by the library (if returned via out-parameter) or by the caller; either
 * way, wolfcert_buffer_free() only releases the `data` pointer and does
 * NOT free the outer struct. */
typedef struct {
    uint8_t* data;
    size_t   len;
    void*    heap;    /* heap used for `data`; NULL = default */
} WolfCertBuffer;

WOLFCERT_API void wolfcert_buffer_free(WolfCertBuffer* buf);

#ifdef __cplusplus
}
#endif

#endif /* WOLFCERT_TYPES_H */
